export const SUCCESS_FEATCHING_DATA = "SUCCESS_FEATCHING_DATA";
export const FAIL_TO_FATCH_DATA = "FAIL_TO_FATCH_DATA";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_BOOK = "SET_SEARCH_BOOK";
export const SET_CATEGORY_QUERY = " SET_CATEGORY_QUERY";
export const SET_AUTHOR_QUERY = " SET_CATEGORY_QUERY";

export const SUCCESS_FETCHING_CATEGORY = "SUCCESS_FETCHING_CATEGORY";
export const FAIL_TO_FETCH_CATEGORY = "FAIL_TO_FETCH_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

export const SUCCESS_FETCHING_BOOK = "SUCCESS_FETCHING_BOOK";
export const FAIL_TO_FETCH_BOOK = "FAIL_TO_FETCH_BOOK";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";

export const SUCCESS_FETCHING_AUTHOR = "SUCCESS_FETCHING_AUTHOR";
export const FAIL_TO_FETCH_AUTHOR = "FAIL_TO_FETCH_AUTHOR";
export const ADD_AUTHOR_SUCCESS = "ADD_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";

export const SIGN_UP_SUCCESS = "REGISTER_SUCCESS";
export const SIGN_UP_ERROR = "REGISTER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
